# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20171019_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='max_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='max_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='min_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='min_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='loss_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='reward_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=5),
        ),
    ]
