# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_questionstarted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstarted',
            name='did_start',
        ),
    ]
