# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
