# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20171014_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
